config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  # get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # resources :users
  resources :sessions
  resources :snipes do
    member do
      get 'force_bid'
    end
  end

  namespace :admin do
    resources :ebay_items
    resources :snipes
    resources :users
    root to: 'ebay_items#index'
  end

  root to: 'snipes#index'
end

app/models/snipe.rb
class Snipe < ApplicationRecord

  belongs_to :user
  belongs_to :ebay_item

  register_currency :gbp
  monetize :max_amount_cents, allow_nil: true

  validates_presence_of :user
  validates_uniqueness_of :ebay_item, scope: :user
  validate :check_amount_is_enough

  validate :ebay_item_xor_ebay_item_input

  attr_accessor :ebay_item_input
  before_validation :assign_ebay_item, if: :ebay_item_input

  scope :upcoming, -> {
    joins(:ebay_item).merge(EbayItem.upcoming).includes(:ebay_item)
  }

  def state
    if max_amount_cents.blank?
      "watching"
    elsif max_amount >= ebay_item.min_bid_price
      "valid"
    else
      "too_low"
    end
  end

  def bid!
    raise "BID TOO HIGH?" if max_amount.to_f > 10
    EbayClient.bid!(
      user.username,
      user.ebay_login_data['cookies'],
      user.ebay_login_data['useragent'],
      ebay_item_id,
      max_amount.to_f
    )
    ebay_item.scrape!
  end

private

  def ebay_item_xor_ebay_item_input
    unless ebay_item.blank? ^ ebay_item_input.blank?
      errors.add(:base, "Specify either an ebay_item or ebay_item_input, not both")
    end
  end

  def check_amount_is_enough
    if state != 'watching' and max_amount < ebay_item.min_bid_price
      errors[:amount] << "Must be greater than" \
        " (#{ebay_item.min_bid_price})"
    end
  end

  def assign_ebay_item
    self.ebay_item = EbayItem.get(EbayItem.extract_id(ebay_item_input))
    self.ebay_item_input = nil
  end

end

app/controllers/admin/snipes_controller.rb
class Admin::SnipesController < Admin::AdminController
  def index
    @snipes = Snipe.includes(:user, :ebay_item)
  end
end

app/controllers/snipes_controller.rb
class SnipesController < ApplicationController

  before_action :authorize

  def index
    @snipes = current_user.snipes.upcoming.includes(:ebay_item)
    @snipe = Snipe.new
  end

  def new
    @snipe = Snipe.new
  end

  def edit
    @snipe = Snipe.find(params[:id])
  end

  def create
    @snipe = current_user.snipes.build(snipe_params)
    if @snipe.save
      redirect_to snipes_path, notice: 'created'
    else
      render :new
    end
  end

  def update
    @snipe = Snipe.find(params[:id])
    if @snipe.update_attributes(snipe_params)
      redirect_to snipes_path, notice: 'updated'
    else
      render :edit
    end
  end

  def destroy
    @snipe = Snipe.find(params[:id])
    @snipe.destroy
    redirect_to snipes_path, notice: 'removed'
  end

  def force_bid
    @snipe = Snipe.find(params[:id])
    @snipe.bid!
    redirect_to snipes_path, notice: 'bid placed'
  end

private

  def snipe_params
    params.require(:snipe).permit(:max_amount, :ebay_item_input)
  end

end

app/views/snipes/_new.html.erb
<%= form_for Snipe.new, id: 'add-item-form', remote: false do |f| %>
  <%= f.text_field :ebay_item_input, placeholder: 'eBay URL or Item ID', autocomplete: 'off', autofocus: true %>
  <%= f.submit "Track Item" %>
<% end %>

app/views/snipes/edit.html.erb
<h1><%= @snipe.ebay_item.name %></h1>

<p>Min price: <%= @snipe.ebay_item.min_bid_price.format %></p>

<% if @snipe.errors.any? %>
<p><%= @snipe.errors.messages %></p>
<% end %>

<%= form_for @snipe do |f| %>
  <%= f.text_field :max_amount, placeholder: "#{@snipe.ebay_item.min_bid_price} or more", autofocus: true, autocomplete: 'off', type: 'number', step: 'any' %>
  <%= f.submit %>
<% end %>

app/views/snipes/index.html.erb
<table>
  <thead>
    <tr>
      <th><%= check_box_tag :check_all_items, 'all' %></th>
      <th colspan="7"></th>
<!--       <th id="table-header-name">Name</th>
      <th id="table-header-ends">Ends</th>
      <th id="table-header-current-price">Current Price</th> -->
<!--       <th id="table-header-bids">Bids</th>
      <th id="table-header-min-bid-required">Snipe</th> -->
      <!-- <th id="table-header-my-snipe">My Snipe</th> -->
      <!-- <th id="table-header-state">State</th> -->
    </tr>
  </thead>
  <tbody>
    <% @snipes.each do |snipe| %>
      <tr class="ebay_item-<%= snipe.ebay_item.id %>">
        <td rowspan="2"><%= check_box_tag :item, snipe.id %></td>
        <td rowspan="2"><div class="image" style="background-image: url('<%= snipe.ebay_item.img %>');"></div></td>
        <td colspan="6" class="id"><%= link_to snipe.ebay_item, snipe.ebay_item.url, class: 'item-name' %></td>
        <!-- <th class="state"><%= link_to snipe.state, edit_snipe_path(snipe) %></th> -->
      </tr><tr class="ebay_item-<%= snipe.ebay_item.id %>">
        <td class="ends_at" colspan="3"><%= timeago snipe.ebay_item.ends_at %></td>
        <td class="number_of_bids"><%= snipe.ebay_item.number_of_bids %> Bid</td>

        <td class="bid_price">
          <%= snipe.ebay_item.bid_price %>
          <span class="min_bid_price"><%= snipe.ebay_item.min_bid_price %></span>
        </td>
        <td class="max_amount">
          <strong><%= snipe.max_amount %></strong>
          <%= link_to snipe.state, edit_snipe_path(snipe) %> /
          <%= link_to 'bid', force_bid_snipe_path(snipe), data: { confirm: 'are you sure you want place your bid early on this item?' } %> /
          <%= link_to 'remove', snipe, method: :delete, class: 'remove' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/snipes/new.html.erb
<% if @snipe.errors.any? %>
<p><%= @snipe.errors.messages %></p>
<% end %>

<%= form_for @snipe do |f| %>
  <div class="input"><%= f.text_field :ebay_item_input %></div>
  <%= f.submit %>
<% end %>