config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  # get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # resources :users
  resources :sessions
  resources :snipes do
    member do
      get 'force_bid'
    end
  end

  namespace :admin do
    resources :ebay_items
    resources :snipes
    resources :users
    root to: 'ebay_items#index'
  end

  root to: 'snipes#index'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin :: Squirrul</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => 'reload' %>
  </head>
  <body>
    <header>
      <ul>
        <li><%= link_to "Ebay Items", admin_ebay_items_path %></li>
        <li><%= link_to "Users", admin_users_path %></li>
        <li><%= link_to "Snipes", admin_snipes_path %></li>

        <li><%= link_to "Log Out", logout_path %></li>
      </ul>
    </header>
    <div id="main" role="main"><%= yield %></div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Squirrul</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <header>
      <% if current_user %>
        <%= render "snipes/new" %>
        <div id="user-info">Logged in as <strong><%= current_user.username %></strong>. <%= link_to "Log Out", logout_path %></div>
      <% else %>
        <%#= link_to "Sign Up", signup_path %>
        <%= link_to "Log In", login_path %>
      <% end %>
    </header>
    <div id="main" role="main"><%= yield %></div>
    <footer>© 2016 Squirrul. eBay® is a registered trademark of eBay, Inc. Squirrul is in no way affiliated with eBay, Inc.</footer>
  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'sessions', media: 'all', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <div id="main" role="main"><%= yield %></div>
  </body>
</html>